"""The controllable-feature registry — one source of truth for every knob a user may tune.

A *controllable feature* is a runtime behavior a user can enable, disable, or
tune per run, expressed as one or more ``MO_*`` / ``MINI_ORK_*`` env knobs, with
a declared cost multiplier. The same registry feeds three surfaces that used to
each keep their own hand-written list:

* the ``mini-ork features`` subcommand (a human reads it),
* the generated block inside ``skills/wizard/SKILL.md`` (the orchestrator reads
  it while walking a user through a run), and
* the ``/wizard`` ACP command (the Thread renders it).

**Add a feature once, in one place.** Call :func:`register_feature` with a
:class:`Feature`; it appears in all three. The skill block is regenerated by
``mini-ork features --markdown``, and a drift check fails when the committed
block is stale — so a feature that is registered but not synced into the skill
is a *red gate*, not a silent omission. That is the "added automatically"
guarantee: nothing enumerates features by hand, so nothing can forget one.

Cost policy (:data:`PREMIUM_THRESHOLD`). A feature is **premium** when enabling
it multiplies run cost by more than 1.5× on its own. Premium features are OFF by
default for wizard-launched runs and require an explicit opt-in; baseline
features (≤1.5×) keep their existing defaults. :func:`premium_unselected`
returns the premium features a selection turned on without opting in — the
launch gate's input.

Read-only and stdlib-only on purpose: the CLI, the ACP command, and the skill
generator all import this on hot paths, so it must stay cheap and dependency-free.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Mapping

#: A feature whose multiplier exceeds this is *premium* — off unless opted in.
PREMIUM_THRESHOLD = 1.5

#: Value kinds a feature's knob can take.
KIND_BOOL = "bool"  # on/off
KIND_COUNT = "count"  # an int the user tunes; cost scales with it
KIND_TEXT = "text"  # free-form (e.g. a lane list); "count" is its token count

#: How a feature's multiplier grows with its count.
COST_FIXED = "fixed"  # multiplier is constant while enabled (bool features)
COST_ADDITIVE = "additive"  # 1 + per_unit*count  (extra calls on top of the node)
COST_PARALLEL = "parallel"  # per_unit*count       (count calls instead of one)

_VALUE_KINDS = frozenset({KIND_BOOL, KIND_COUNT, KIND_TEXT})
_COST_MODELS = frozenset({COST_FIXED, COST_ADDITIVE, COST_PARALLEL})

_OFF = (None, "", "0")


@dataclass(frozen=True)
class Feature:
    """One user-controllable run behavior, and what it costs.

    ``knobs`` maps an env var to the value it takes when the feature is enabled
    — for :data:`KIND_BOOL` that is the whole switch; for other kinds these are
    the *co-knobs* that switch on with it. ``count_knob`` names the env var the
    user's chosen value is written to (the count, or the lane list for
    :data:`KIND_TEXT`).
    """

    id: str
    label: str
    description: str
    knobs: Mapping[str, str] = field(default_factory=dict)
    kind: str = KIND_BOOL
    count_knob: str = ""
    default: str = ""
    cost_model: str = COST_FIXED
    cost_multiplier: float = 1.0  # COST_FIXED only
    cost_per_unit: float = 0.0  # additive/parallel
    unit: str = ""
    applies_to: tuple[str, ...] = ()  # () = every recipe
    docs: str = "docs/operator/feature-flags.md"

    def __post_init__(self) -> None:
        if self.kind not in _VALUE_KINDS:
            raise ValueError(f"feature {self.id!r}: unknown kind {self.kind!r}")
        if self.cost_model not in _COST_MODELS:
            raise ValueError(f"feature {self.id!r}: unknown cost_model {self.cost_model!r}")
        if self.cost_model != COST_FIXED and self.cost_per_unit <= 0.0:
            raise ValueError(f"feature {self.id!r}: {self.cost_model} needs cost_per_unit > 0")

    # ── derived ──────────────────────────────────────────────────────────────

    def count_of(self, value: str | None) -> int:
        """The unit count for ``value`` (0 when off)."""
        if value in _OFF:
            return 0
        if self.kind == KIND_COUNT:
            try:
                return max(0, int(str(value)))
            except (TypeError, ValueError):
                return 0
        if self.kind == KIND_TEXT:
            return len(str(value).split())
        return 1  # bool, enabled

    def multiplier(self, value: str | None) -> float:
        """This feature's marginal factor on run cost at ``value`` (≥1.0)."""
        n = self.count_of(value)
        if n == 0:
            return 1.0
        if self.cost_model == COST_FIXED:
            return max(1.0, self.cost_multiplier)
        if self.cost_model == COST_ADDITIVE:
            return 1.0 + self.cost_per_unit * n
        return max(1.0, self.cost_per_unit * n)  # parallel

    @property
    def tier(self) -> str:
        """``"premium"`` when this feature's default already exceeds the threshold."""
        return "premium" if self.multiplier(self.default) > PREMIUM_THRESHOLD else "baseline"

    def applies(self, recipe: str | None) -> bool:
        return not self.applies_to or (recipe or "") in self.applies_to

    def to_json(self) -> dict[str, Any]:
        return {
            "id": self.id,
            "label": self.label,
            "description": self.description,
            "kind": self.kind,
            "knobs": dict(self.knobs),
            "count_knob": self.count_knob,
            "default": self.default,
            "unit": self.unit,
            "cost_model": self.cost_model,
            "cost_multiplier": round(self.multiplier(self.default), 3),
            "tier": self.tier,
            "applies_to": list(self.applies_to),
            "docs": self.docs,
        }


# ── registry ────────────────────────────────────────────────────────────────

CONTROLLABLE_FEATURES: dict[str, Feature] = {}


def register_feature(feature: Feature) -> Feature:
    """Add ``feature`` to the registry, keyed by id.

    Registration is how *any* module announces a new user-facing knob. The CLI,
    the wizard skill, and ``/wizard`` all enumerate this dict, so a call here is
    the whole wiring.
    """
    if not feature.id:
        raise ValueError("feature id required")
    CONTROLLABLE_FEATURES[feature.id] = feature
    return feature


def get_feature(feature_id: str) -> Feature | None:
    return CONTROLLABLE_FEATURES.get(feature_id)


def features_for(recipe: str | None = None) -> list[Feature]:
    """Every feature that applies to ``recipe`` (and the always-applicable ones)."""
    return [f for f in CONTROLLABLE_FEATURES.values() if f.applies(recipe)]


# ── cost math ───────────────────────────────────────────────────────────────


def effective_multiplier(selection: Mapping[str, str]) -> float:
    """Product of the selected features' multipliers — the projected run cost.

    ``selection`` maps feature id → chosen value (``""`` / ``"0"`` = off). A
    baseline-only selection stays near 1.0; enabling a premium feature jumps it.
    """
    total = 1.0
    for fid, value in selection.items():
        feat = CONTROLLABLE_FEATURES.get(fid)
        if feat is not None:
            total *= feat.multiplier(value)
    return round(total, 3)


def premium_unselected(selection: Mapping[str, str]) -> list[Feature]:
    """Premium features the selection turned on without an opt-in.

    The launch gate strips these (downgrade-to-baseline) unless the caller set
    ``MO_ACCEPT_PREMIUM=1`` — the "manually enabled by the user" policy.
    """
    out: list[Feature] = []
    for fid, value in selection.items():
        feat = CONTROLLABLE_FEATURES.get(fid)
        if feat is None or feat.multiplier(value) <= PREMIUM_THRESHOLD:
            continue
        out.append(feat)
    return out


def resolve_selection(
    selection: Mapping[str, str], *, accept_premium: bool = False
) -> dict[str, str]:
    """Turn a feature selection into the env overrides a run should be launched with.

    Premium features are dropped (with their co-knobs) unless ``accept_premium``.
    Off features contribute nothing, so the returned env is minimal and explicit.
    """
    blocked = {f.id for f in premium_unselected(selection)} if not accept_premium else set()
    env: dict[str, str] = {}
    for fid, value in selection.items():
        feat = CONTROLLABLE_FEATURES.get(fid)
        if feat is None or fid in blocked or value in _OFF:
            continue
        env.update({k: str(v) for k, v in feat.knobs.items()})
        if feat.count_knob:
            env[feat.count_knob] = str(value)
        elif feat.kind == KIND_BOOL and len(feat.knobs) == 0:
            env[f"MO_{fid.upper()}"] = "1"
    return env


def _enabled_value(feat: Feature, env: Mapping[str, str]) -> str:
    """The value a feature is switched on with inside ``env`` ("" when absent)."""
    for k in feat.knobs:
        if env.get(k) not in _OFF:
            return "1" if feat.kind == KIND_BOOL else str(env.get(feat.count_knob) or feat.default)
    if feat.count_knob and env.get(feat.count_knob) not in _OFF:
        return str(env[feat.count_knob])
    return ""


def gate_env(
    env: Mapping[str, str], *, accept_premium: bool = False
) -> tuple[dict[str, str], list[str]]:
    """Strip premium-feature knobs from an env dict unless the user opted in.

    This is the launch gate: a run carries its feature set as env overrides, so
    a premium feature (one that adds more than :data:`PREMIUM_THRESHOLD` on its
    own) is removed — with all its knobs — when ``MO_ACCEPT_PREMIUM`` is not
    set. Returns ``(filtered_env, blocked_feature_ids)``; the caller surfaces
    ``blocked`` so the user knows what was dropped and how to enable it.
    """
    if accept_premium:
        return dict(env), []
    out = dict(env)
    blocked: list[str] = []
    for feat in CONTROLLABLE_FEATURES.values():
        value = _enabled_value(feat, env)
        if not value or feat.multiplier(value) <= PREMIUM_THRESHOLD:
            continue
        blocked.append(feat.id)
        for k in feat.knobs:
            out.pop(k, None)
        if feat.count_knob:
            out.pop(feat.count_knob, None)
    return out, blocked


# ── rendering (the skill block + the /wizard table share this) ───────────────


def _fmt_multiplier(feat: Feature) -> str:
    m = feat.multiplier(feat.default)
    if feat.cost_model == COST_ADDITIVE:
        return f"×{m:g} (1+{feat.cost_per_unit:g}×{feat.unit or 'unit'})"
    if feat.cost_model == COST_PARALLEL:
        return f"×{m:g} ({feat.cost_per_unit:g}×{feat.unit or 'unit'})"
    return f"×{m:g}"


def catalogue_markdown(recipe: str | None = None) -> str:
    """A stable markdown table of the controllable features.

    Written between the generated-block sentinels in ``skills/wizard/SKILL.md``
    and echoed by ``/wizard`` — so both stay in step with the registry by
    construction. With ``recipe=None`` every feature is listed; a per-recipe
    call narrows to that recipe's features.
    """
    feats = (
        list(CONTROLLABLE_FEATURES.values()) if recipe is None else features_for(recipe)
    )
    groups = (
        ("Baseline — default on", [f for f in feats if f.tier == "baseline"]),
        ("Premium — opt-in (>1.5×)", [f for f in feats if f.tier == "premium"]),
    )
    lines: list[str] = []
    for title, group in groups:
        if not group:
            continue
        lines.append(f"**{title}**")
        lines.append("")
        lines.append("| Feature | id | knob(s) | cost | default | scope |")
        lines.append("|---|---|---|---|---|---|")
        for f in sorted(group, key=lambda x: x.id):
            knob_parts = [f"`{k}`" for k in f.knobs]
            if f.count_knob:
                knob_parts.append(f"`{f.count_knob}`")
            knob = "<br>".join(knob_parts) or "—"
            if f.kind == KIND_BOOL:
                default = f.default or "off"
            else:
                default = f.default or "—"
            scope = ", ".join(f.applies_to) if f.applies_to else "all recipes"
            lines.append(
                f"| {f.label} | `{f.id}` | {knob} | {_fmt_multiplier(f)} | {default} | {scope} |"
            )
        lines.append("")
    return "\n".join(lines).rstrip() + "\n"


def catalogue_json(recipe: str | None = None) -> dict[str, Any]:
    """The machine form: ``{premium_threshold, features: [...]}``."""
    return {
        "premium_threshold": PREMIUM_THRESHOLD,
        "features": [f.to_json() for f in features_for(recipe)],
    }


# ── built-ins ───────────────────────────────────────────────────────────────
# Seeded from docs/operator/feature-flags.md. A premium feature here is one
# whose own default multiplier exceeds PREMIUM_THRESHOLD (review panel ≈ 3
# lanes, the code-arm probe scorer ≈ 2 full arms, recursion ≈ N iterations).


def _load_builtins() -> None:
    blue = [
        # ── baseline ─────────────────────────────────────────────────────────
        Feature(
            id="plan_qa_gate",
            label="Plan Q&A gate",
            description="Block a run on needs_answers plans until the user answers (exit 6).",
            knobs={"MINI_ORK_EXECUTE_GATE": "1"},
            default="1",
            cost_multiplier=1.0,
        ),
        Feature(
            id="learning_writeback",
            label="GRPO learning writeback",
            description="Write the run's advantage back into the learning loop after it ends.",
            knobs={"MO_LEARNING_WRITEBACK": "1"},
            default="1",
            cost_multiplier=1.0,
        ),
        Feature(
            id="reward_stamp",
            label="Reward stamp",
            description="Stamp a normalized reward on execution traces.",
            knobs={"MO_REWARD_STAMP": "1"},
            default="1",
            cost_multiplier=1.0,
        ),
        Feature(
            id="prm_score",
            label="PRM scoring",
            description="Process-reward heuristic scoring on traces.",
            knobs={"MO_PRM_SCORE": "1"},
            default="1",
            cost_multiplier=1.05,
        ),
        Feature(
            id="oracle_gates",
            label="Oracle gates (auto)",
            description="Run the certify oracle gates automatically at publish.",
            knobs={"MO_ORACLE_GATES_AUTO": "1"},
            default="1",
            cost_multiplier=1.2,
        ),
        Feature(
            id="assay_relations",
            label="Metamorphic relations",
            description="Relations term in the certify oracle; vetoes a would-be PROVEN on a broken relation.",
            knobs={"MO_ASSAY_RELATIONS": "1"},
            kind=KIND_COUNT,
            count_knob="MO_ASSAY_RELATIONS_K",
            default="3",
            cost_model=COST_ADDITIVE,
            cost_per_unit=0.07,
            unit="relations",
        ),
        Feature(
            id="assay_differential",
            label="Differential assay",
            description="Re-execute the change N times under perturbation to test stability.",
            knobs={"MO_ASSAY_DIFFERENTIAL": "1"},
            kind=KIND_COUNT,
            count_knob="MO_ASSAY_DIFFERENTIAL_N",
            default="6",
            cost_model=COST_ADDITIVE,
            cost_per_unit=0.03,
            unit="executions",
        ),
        # ── premium (>1.5×) ──────────────────────────────────────────────────
        Feature(
            id="review_panel",
            label="Review panel",
            description="Fan a review node across N judge lanes instead of one.",
            knobs={},
            kind=KIND_TEXT,
            count_knob="MO_REVIEW_PANEL",
            default="codex kimi glm",
            cost_model=COST_PARALLEL,
            cost_per_unit=1.0,
            unit="lanes",
        ),
        Feature(
            id="code_arm_scorer",
            label="Code-arm probe scorer",
            description="Score an apply candidate by running baseline + candidate arms (2 full runs per probe).",
            knobs={"MO_APPLY_SCORER": "code", "MO_APPLY_CODE_PATCH": ""},
            kind=KIND_COUNT,
            count_knob="MO_APPLY_PROBE_MAX_TASKS",
            default="1",
            cost_model=COST_PARALLEL,
            cost_per_unit=2.0,
            unit="probes",
        ),
        Feature(
            id="recursion",
            label="Recursion",
            description="Iterate the recipe up to N times until convergence, under a total budget cap.",
            knobs={"MO_RECURSION_BUDGET_CAP_TOTAL_USD": "15"},
            kind=KIND_COUNT,
            count_knob="MO_RECURSION_MAX_ITERATIONS",
            default="3",
            cost_model=COST_PARALLEL,
            cost_per_unit=1.0,
            unit="iterations",
            applies_to=("recursive-self-improve",),
        ),
    ]
    for f in blue:
        register_feature(f)


_load_builtins()
